"""Add event_id to blocks table with batch mode

Revision ID: 1ce9899b2ddd
Revises: b3aa9ea4f88a
Create Date: 2025-07-14 13:02:28.860752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ce9899b2ddd'
down_revision: Union[str, None] = 'b3aa9ea4f88a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=False, server_default='1'))
        batch_op.create_foreign_key('fk_blocks_event_id', 'events', ['event_id'], ['id'])
        batch_op.create_index('idx_blocks_event_language', ['event_id', 'language_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.drop_index('idx_blocks_event_language')
        batch_op.drop_constraint('fk_blocks_event_id', type_='foreignkey')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###
