"""is_looking_for_friends

Revision ID: 6d3cb10d5d11
Revises: 30b7eab32484
Create Date: 2025-04-07 04:37:06.459111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d3cb10d5d11'
down_revision: Union[str, None] = '30b7eab32484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_looking_for_friends', sa.Boolean(), nullable=False, server_default='False'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_looking_for_friends')
    # ### end Alembic commands ###
