"""add_hint

Revision ID: 767d14c69eea
Revises: c9a2e591782a
Create Date: 2025-03-29 18:07:57.060316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '767d14c69eea'
down_revision: Union[str, None] = 'c9a2e591782a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('hint_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'hint_path')
    # ### end Alembic commands ###
