"""delete_extra_longread

Revision ID: 773c156d4d4d
Revises: 8b46a1ddef6f
Create Date: 2025-05-03 13:17:59.192722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '773c156d4d4d'
down_revision: Union[str, None] = '8b46a1ddef6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'longread_ru', new_column_name='longread')
    op.drop_column('questions', 'longread_en')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('longread_en', sa.VARCHAR(), nullable=True))
    op.alter_column('questions', 'longread', new_column_name='longread_ru')
    # ### end Alembic commands ###
