"""add_longread

Revision ID: 8b46a1ddef6f
Revises: 40b42964638f
Create Date: 2025-05-03 12:37:29.928063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b46a1ddef6f'
down_revision: Union[str, None] = '40b42964638f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('longread_ru', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('longread_en', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'longread_en')
    op.drop_column('questions', 'longread_ru')
    # ### end Alembic commands ###
