"""quest_date

Revision ID: 8d1c9c4192ae
Revises: 767d14c69eea
Create Date: 2025-04-04 01:29:00.905884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d1c9c4192ae'
down_revision: Union[str, None] = '767d14c69eea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('events', sa.Column('end_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'end_time')
    op.drop_column('events', 'start_time')
    # ### end Alembic commands ###
