"""add_additional_field_value_to_answers

Revision ID: b3aa9ea4f88a
Revises: 133af3bb6219
Create Date: 2025-07-13 21:10:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3aa9ea4f88a'
down_revision: Union[str, None] = '133af3bb6219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('additional_field_value', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'additional_field_value')
    # ### end Alembic commands ###
