{
 "title": "FastAPI Overview",
 "tags": [
  "prometheus",
  "fastapi"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "HTTP Requests Total (event_name)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_requests_total{event_name!=''}",
     "legendFormat": "{{event_name}}"
    }
   ]
  },
  {
   "title": "HTTP Request Duration (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[1m])) by (le, event_name))",
     "legendFormat": "p95 {{event_name}}"
    }
   ]
  },
  {
   "title": "HTTP Exceptions Total (event_name)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "http_exceptions_total{event_name!=''}",
     "legendFormat": "{{event_name}}"
    }
   ]
  }
 ]
}